name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides customizable video player controls that support android, ios and web.
version: 0.9.7
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  lottie: ^2.2.0  
  # services
  video_player: ^2.5.1
  http: ^0.13.5  
  get: ^4.6.5  
  wakelock: ^0.6.2 
  universal_html: ^2.0.8 
  youtube_explode_dart: ^1.12.3
  flutter_command: ^2.0.1
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  assets:
    - assets/
